MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/root/shared-nvme/data/jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  NO_MARGIN: False
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  DIRECT: 1
  ID_LOSS_WEIGHT: 0.25
  TRIPLET_LOSS_WEIGHT: 1.0



  

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST:  [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.4 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('RGBNT201')
  ROOT_DIR: ('/root/shared-nvme/data/')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 8
  NUM_WORKERS: 8
SOLVER:
  OPTIMIZER_NAME: 'Adam'
  BASE_LR: 0.000035
  IMS_PER_BATCH: 64
  WARMUP_ITERS: 5
  MARGIN: 0.8
  MAX_EPOCHS: 40
  SEED: 42
  STEPS: (20, 50)
  
  
  
  
  

  

TEST:
  RE_RANKING: 'no'
  WEIGHT: '/root/shared-nvme/PCL/logs/rgbnt201/proxy_clip_tta/850_best.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  # MISS: 'R'
  IMS_PER_BATCH: 64
  TTA_epoch: 70



OUTPUT_DIR: './logs_pro/rgbnt201/Heat'
