MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH:  '/root/shared-nvme/data/jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: False
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  DIRECT: 0 # We find that for vehicle reid, indirect is better than direct


INPUT:
  SIZE_TRAIN: [128, 256]
  SIZE_TEST:  [128, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.0 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('WMVEID863')
  ROOT_DIR: ('/root/shared-nvme/data/')
 


DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 2
  NUM_WORKERS: 8
  
SOLVER:
  OPTIMIZER_NAME: 'Adam'
  IMS_PER_BATCH: 64
  BASE_LR: 0.00035
  WARMUP_ITERS: 10
  LOG_PERIOD: 10
  MARGIN: 0.5




TEST:
  WEIGHT: './logs/WMVEID863/new/transformerbest.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  IMS_PER_BATCH: 64

OUTPUT_DIR: './logs/WMVEID863/proxy_vit_tta'


